### ISSUE TITLE
Stockfish integration

### ISSUE THREAD

**Issue by oganm** [curso-r/chess#1]
I am not actively maintaining this package anymore but I did work on a [stockfish](https://github.com/oganm/stockfisher) integration before, though its based on rchess. if you'd want to describe the user facing API that you want to work with on your end, I can probably translate it with relative ease.

**Comment by clente** [comment]
Hey, oganm. Is your package on CRAN? That would be important since I'm about to submit `{chess}`.

**Comment by oganm** [comment]
Nope and I wasn't  planning to submit it. that's partially why I was offering to add the functionality here. 

Though I could add support for {chess} within my package then go on to Cran if you think that would be better. Just commented after seeing stockfish in your todo list

**Comment by clente** [comment]
Thanks for the offer! I'll take a look at the API and think about it :)

**Comment by clente** [comment]
Will reopen if necessary.
