### ISSUE TITLE
It's not working for me

### ISSUE THREAD

**Issue by DatWins** [curso-r/chess#11]
I try to follow your documentation but it doesn't work at all. Here's the image
![Capture](https://user-images.githubusercontent.com/44272120/128077415-673b794d-a025-428e-99d8-82d670334f37.PNG)

Please let me know what I am doing wrong. Thank you.

**Comment by clente** [comment]
I really need more information. Did you load the package? Did you run `chess::install_chess()`?

**Comment by DatWins** [comment]
Yes. I follow your instruction.

**Comment by clente** [comment]
Could you please try running `library(chess)` before running the commands you submitted?

**Comment by DatWins** [comment]
![Capture](https://user-images.githubusercontent.com/44272120/128086144-b03fe34b-bcac-4472-b72b-02bbcca160cd.PNG)

**Comment by clente** [comment]
You have to read the error message. It tells you to install miniconda and gives you a yes/no prompt.
