### ISSUE TITLE
can't run on google colab

### ISSUE THREAD

**Issue by sugizo** [curso-r/chess#12]
can't run on google colab, start from scratch

```
install.packages("chess")
any(grepl("chess", installed.packages() ) )
library("chess")
```

also tried this

```
remotes::install_github("curso-r/chess")
any(grepl("chess", installed.packages() ) )
library("chess")
```

but got same result

![image](https://github.com/curso-r/chess/assets/2418295/618c053d-93c5-4050-b342-1c4005596784)

best regards

**Comment by clente** [comment]
It seems like there is a problem with rsvg, which is one of chess's dependencies. If it doesn't install correctly, then chess won't either.

I'd check if there is something wrong on their side first.
