### ISSUE TITLE
Can't install python-chess?

### ISSUE THREAD

**Issue by hadley** [curso-r/chess#3]
```
chess::install_chess()
...
#> PackagesNotFoundError: The following packages are not available from current channels:
#> 
#>   - chess
#> 
#> Current channels:
#> 
#>   - https://conda.anaconda.org/conda-forge/osx-64
#>   - https://conda.anaconda.org/conda-forge/noarch
#>   - https://repo.anaconda.com/pkgs/main/osx-64
#>   - https://repo.anaconda.com/pkgs/r/osx-64
#>   - https://repo.anaconda.com/pkgs/main/noarch
#>   - https://repo.anaconda.com/pkgs/r/noarch
```

I'm doing this just to double check that https://github.com/r-lib/testthat/pull/1261 won't break your package, so while you might want to look into my installation issue, I'd also appreciate you just checking to see if the testthat change breaks chess.

**Comment by clente** [comment]
@hadley, could you please try the following installation method? It was my first time adding `{reticulate}` to a package, so I might have done something wrong.

```r
reticulate::py_install("chess", python_version = "3.8", pip = TRUE)
```

**Comment by hadley** [comment]
That worked, thanks!

**Comment by clente** [comment]
I installed `{testthat}` with the following command:

```r
remotes::install_github("r-lib/testthat#1261")
```

and everything seems to work as expected! I got a weird message, but I feel like that has more to do with my tests than with the package itself. I had an old snapshot lying around and it told me it would delete it; but it didn't :thinking:

```r
devtools::test()
#> Loading chess
#> Testing chess
#> ✓ |  OK F W S | Context
#> ✓ |  24       | annotations [1.6 s]                                        
#> ✓ |  22       | game [1.1 s]                                               
#> ✓ |   6       | io [1.0 s]                                                 
#> ✓ |  31       | meta [0.4 s]                                               
#> 
#> ══ Results ═══════════════════════════════════════
#> Duration: 4.1 s
#> 
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 83 ]
#> Deleting unused snapshots:
#> * _snaps/visual
#> * _snaps/visual
```

Let me know if you need any session information.

**Comment by hadley** [comment]
Yeah, I see that problem too. I'll take a look tomorrow. Thanks!

**Comment by hadley** [comment]
Should be fixed now 😄
